Server/WebSignalR/WebSignalR/Controllers/RoomActivityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSignalR.Common.DTO;
using WebSignalR.Common.Entities;
using WebSignalR.Common.Extension;
using WebSignalR.Common.Interfaces;

namespace WebSignalR.Controllers
{
	[Authorize]
	public class RoomActivityController : MvcController
	{
		public RoomActivityController(IUnityOfWork unity)
		{
			Ensure.Argument.NotNull(unity, "unity");
			base._unity = unity;
		}

		public ActionResult Index(string roomName)
		{
			if (roomName != null)
			{
				Room room = Unity.GetRepository<Room>().Get(x => x.Name == roomName).FirstOrDefault();
				if (room != null)
				{
					ViewData["RoomId"] = room.Id;
					ViewData["RoomName"] = room.Name;
					Session["RoomId"] = room.Id;
					Session["RoomName"] = room.Name;
				}
			}

			ViewData["User"] = User as Infrastructure.CustomPrincipal;
			ViewData["UserId"] = (User as Infrastructure.CustomPrincipal).UserId;
			ViewData["IsAdmin"] = (User as Infrastructure.CustomPrincipal).IsInRole("Admin");
			string baseAddress = Request.Url.GetLeftPart(UriPartial.Authority) + Url.Content("~");
			//string baseAddress2 = new Uri(Request.Url, Url.Content("~")).ToString();
			TempData["baseAddress"] = baseAddress;
			return View();
		}

		[Authorize]
		[HttpPost]
		public ActionResult Upload(FormCollection formCollection)
		{
			if (Request != null)
			{
				int rid = -1;
				if (Request.Headers.AllKeys.Contains("RoomId"))
				{
					rid = int.Parse(Request.Headers.Get("roomId"));
				}
				else if (Session["RoomId"] != null)
				{
					rid = (int)Session["RoomId"];
				}

				HttpPostedFileBase file = Request.Files["UploadedFile"];
				if ((file != null) && (file.ContentLength > 0) && !string.IsNullOrEmpty(file.FileName))
				{
					if (rid != -1)
					{
						try
						{
							IVotesProvider provider = new Infrastructure.XmlVotesProvider();
							provider.Source = file.InputStream;
							ICollection<VoteItem> data = provider.GetVotes();
							Room room = Unity.GetRepository<Room>().Get(x => x.Id == rid).FirstOrDefault();
							foreach (var item in data)
							{
								item.HostRoom = room;
								room.ItemsToVote.Add(item);
							}
							Unity.Commit();

							RoomDto dto = AutoMapper.Mapper.Map<RoomDto>(room);
							base.AgileHubConnection.Group(dto.Name).onRoomStateChanged(dto);
						}
						catch (Exception ex)
						{
							return Json(new { Status = ex.Message });
						}
					}
					return Json(new { Status = "Ok" });
				}
				return Json(new { Status = "No file" });
			}
			else
				return Json(new { Status = "Failed" });
		}

		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
	}
}

Server/WebSignalR/WebSignalR/Views/RoomActivity/Index.cshtml
@using WebSignalR.Infrastructure
@{
	ViewBag.Title = "Room activity";
	Layout = "~/Views/Shared/_Layout.cshtml";
	var user = ViewData["User"] as CustomPrincipal;
	var uid = (int)ViewData["UserId"];
	var isAdmin = (bool)ViewData["IsAdmin"];
	var roomId = (int)ViewData["RoomId"];
	var roomName = (string)ViewData["RoomName"];
	var baseAddressUrl = (string)TempData["baseAddress"];
}
@functions{
	public string GetAntiForgeryToken()
	{
		string cookieToken, formToken;
		AntiForgery.GetTokens(null, out cookieToken, out formToken);
		return cookieToken + ":" + formToken;
	}
}
@if (@User.Identity.IsAuthenticated)
{
	@section styles{
		@*@Styles.Render("~/Content/koGrid")*@
		@Styles.Render("~/Content/roomActivity")
		@Styles.Render("~/Content/jqueryMenu")
	}
}
<h2>Room Activity View</h2>

@if (User.Identity.IsAuthenticated)
{
	//data-bind="attr: {id: id}
	<p class="error" data-bind="text: error"></p>
	<input id="antiForgeryToken" type="hidden" value="@GetAntiForgeryToken()" />
	<input id="txtBaseAddress2" type="hidden" value="@baseAddressUrl"/>	
	<input id="txtBaseAddress" type="hidden" />	
	<input id="userId" type="hidden" value="@uid" />
	<input id="isAdmin" type="hidden" value="@isAdmin" />
	<input id="roomId" type="hidden" value="@roomId" />
	<input id="roomName" type="hidden" value="@roomName" />
	
	if (User.IsInRole("Admin") || User.IsInRole("ScrumMaster"))
	{
	<div class="navbar navbar-default" role="navigation">
		<div class="navbar-inner">
			<div class="container" style="width: auto;">
				<div class="nav-collapse">
					<a class="btn btn-default" data-bind="click: importQuestions">Import questions</a>
					<a class="btn btn-default" data-bind="click: openVoteItem">Open vote</a>
					<a class="btn btn-default" data-bind="click: closeVoteItem">Close vote</a>
					<a class="btn btn-default" data-bind="click: changeRoomState">Change room state</a>
					<a class="btn btn-default" data-bind="click: submitVoteForItem">Vote for selected</a>
					<a class="btn btn-default" data-bind="click: generateCsv">Get Csv document</a>
				</div>
			</div>
		</div>
	</div>
		
	<div id="importDialog" title="Import questions">
		@Html.Partial("_Import")
	</div>
	<div id="closeVoteDialog" title="Close vote">
		@Html.Partial("_CloseVote")
	</div>
	<div id="changeRoomStateDialog" title="Change room state">
		@Html.Partial("_ChangeRoomState")
	</div>
	<div id="csvPanel" title="Change room state">
		<ul id="csvStateList">
		</ul>
	</div>
	}
	else if (User.IsInRole("User"))
	{
	<div class="navbar navbar-default" role="navigation">
		<div class="navbar-inner">
			<div class="container" style="width: auto;">
				<div class="nav-collapse">
					<a class="btn btn-default" data-bind="click: submitVoteForItem">Vote for selected</a>
				</div>
			</div>
		</div>
	</div>
	}
	
	<div id="voteForItemDialog" title="Submit vote mark">
		@Html.Partial("_VoteForItem")
	</div>
	
	<div class="contextMenu" id="dataGridMenu1">
		<ul>
			<li id="openMenuItem">Open vote item</li>
			<li id="closeMenuItem">Close vote item</li>
		</ul>
	</div>
	
	
	<div id="activityContainer" data-bind="with: roomDtoState">
		<table id="activityTable">
			<thead>
				<tr id="header">
					<th id="questionHeader">Question content (placed below):</th>
					<!-- ko foreach: connectedUsers-->
					<th data-bind="text: name, attr: { id: id }"></th>
					<!-- /ko -->
				</tr>
			</thead>
			<tbody data-bind="foreach: itemsToVote">
				<tr data-bind="attr: { id: id }">
					<td data-bind="text: content, click: function (data, event) { $root.selectedVoteItemChanged($data, event) }"></td>
				</tr>
			</tbody>
		</table>
	</div>
}

@if (@User.Identity.IsAuthenticated)
{
	@section scripts {
		@Scripts.Render("~/bundles/ko-signalr")
		@*@Scripts.Render("~/bundles/koGrid")*@
		<script type="text/javascript" src="~/signalr/hubs"></script>
		@Scripts.Render("~/bundles/agileRoomActivity")
		@Scripts.Render("~/bundles/jqueryuimenu")
	}
}

Server/WebSignalR/WebSignalR/Views/RoomActivity/_ChangeRoomState.cshtml
<h3>Change room state:
</h3>
<form id="changeRoomStateForm">
	<fieldset>
		<legend>Change room state form</legend>
		<ol>
			<li>
				<label for="comboState">Room state:</label>
				<select id="comboState">
					<option value="true">Opened</option>
					<option value="false">Closed</option>
				</select>
			</li>
		</ol>
	</fieldset>
</form>

Server/WebSignalR/WebSignalR/Views/RoomActivity/_CloseVote.cshtml
<h3>
	Close vote item:
</h3>
<form id="closeVoteItemForm">
	<fieldset>
		<legend>Close vote item form</legend>
		<ol>
			<li>
				<label for="txtVoteContent">Mark:</label>
				<input type="text" id="txtVoteItemMark"/>
			</li>
		</ol>
	</fieldset>
</form>

Server/WebSignalR/WebSignalR/Views/RoomActivity/_Import.cshtml
<h2 id="title">Upload</h2>

@using (Html.BeginForm("Upload", "RoomActivity", FormMethod.Post, new { enctype = "multipart/form-data", Id = "importForm" }))
{
	<input type="file" name="UploadedFile" />
	<br />
	<p></p>
	<input type="submit" name="Submit" value="Upload" id="btnUploadFile" />
}

Server/WebSignalR/WebSignalR/Views/RoomActivity/_VoteForItem.cshtml
<h3>Submit vote for item:
</h3>
<form id="submitVoteForm">
	<fieldset>
		<legend>Sumbmit vote</legend>
		<ol>
			<li>
				<label for="txtVoteContent">Vote content:</label>
				<textarea id="voteItemContent"></textarea>
			</li>
			<li>
				<label for="txtVoteContent">Mark:</label>
				<input type="text" id="txtVoteItemMark" />
			</li>
		</ol>
	</fieldset>
</form>